### ISSUE TITLE
UnicodeDecodeError raised on starting server

### ISSUE THREAD

**Issue by HyeongRae** [rishubil/TrickyTowersUtils#8]
This is screenshot of traceback,
![default](https://user-images.githubusercontent.com/22023781/53559955-af108100-3b8e-11e9-8df7-64538c6a70c0.JPG)

**Comment by HyeongRae** [comment]
And this is my config file.
[config.zip](https://github.com/rishubil/TrickyTowersUtils/files/2914590/config.zip)

**Comment by rishubil** [comment]
It may be happened if your hostname of machine contains non-ASCII charactor.
This issue was described at [here](https://bugs.python.org/issue9377).

You can check your hostname by following command on console.
```
hostname
```

If your hostname contains non-ASCII charactor, you should change your hostname.
You can change your hostname by following command on console and **REBOOT YOUR MACHINE**.
(Replace `NEW-NAME` to what you want)
```
wmic computersystem where name="%COMPUTERNAME%" rename name="NEW-NAME"
```
